title: Kadeuk Tech Blog
description: 83년생 엔지니어의 M365 정복기
author: Kadeuk
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
minimal_mistakes_skin: "default"
search: true

# 날짜 표시 형식 한국식으로 변경
locale: "ko-KR"
timezone: "Asia/Seoul"

# 상단 메뉴 연결
data:
  ui-text:
    nav_list_label: "Menu"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

future: true